### ISSUE TITLE
Decouple object and array cases from no-array-destructuring and no-array-subscript rules

### ISSUE THREAD

**Issue by danielnixon** [danielnixon/eslint-plugin-total-functions#28]
- `no-array-destructuring` to become `no-unsafe-array-destructuring` and `no-unsafe-object-destructuring`
- `no-array-subscript` to become `no-unsafe-array-subscript` and `no-unsafe-object-subscript`

**Comment by danielnixon** [comment]
Although the distinction isn't as clear cut as you might hope. What's this, object or array?

```typescript
const arr = [];
arr[length];
```

And this?

```typescript
const obj = { 1: 1 };
obj[1];
```

**Comment by tankers746** [comment]
An array could be determined by `Array.isArray` and the rule would only need to error on numeric indexes. Indexing length on an array using `arr["length"]` isn't unsafe because typescript has us covered.

For objects the example correctly doesn't error and TS infers the type as:
```
{
   1: number
}
```
Once again TS has us covered if we try and access `obj[2]`.

I suppose I'm not sure about the necessity of an object subscript rule?

**Comment by danielnixon** [comment]
> I suppose I'm not sure about the necessity of an object subscript rule?

```typescript
const record: Record<string, string> = { foo: "foo" };
const bar = record["bar"]; // bar has type string, not string | undefined
bar.toUpperCase(); // This explodes at runtime
```

**Comment by tankers746** [comment]
I see, really the issue here isn't subscript access, its index signatures. The example above would also fail when using dot notation. Ideally the rule should just ban all forms of object indexing when an index signature is present as that potentially unsafe.

**Comment by danielnixon** [comment]
>Ideally the rule should just ban all forms of object indexing when an index signature is present as that potentially unsafe.

If we were to do that, how would a user ever get at a property like `@foo` below?

```typescript
const record: Record<"@foo", string> = { "@foo": "foo" };
record.@foo; // Doesn't compile
record."@foo"; // Doesn't compile
const foo = record["@foo"]; // This has to be permitted, right?
```

**Comment by tankers746** [comment]
You would access it the same way you access any other banned form of indexing, using an alternate method to retrieve the value, e.g. a `get` function like the one provided by your total-functions package. Wether the key is `@foo`, `foo` or `0` dot or subscript access is unsafe.


Error:
```
const record: Record<"@foo", string> = { "@foo": "foo" };
const foo = record["@foo"];
```

No index pattern, no error:
```
const record: { '@foo': string } = { '@foo': 'foo' };
const foo = record["@foo"];
```

**Comment by tankers746** [comment]
Your example should work fine and shouldn't error as its not using an index pattern.
`Record<"@foo", string>` is equal to `{ '@foo': string }`
And TS protects us from indexing an object literal incorrectly.

The issue is with index patterns:
`Record<string, string>` is equal to `{ [index: string]: string }`
Which is unsafe as it allows you to index the object with any string and typescript wont return it as potentially undefined (the same issue as arrays).

**Comment by danielnixon** [comment]
I think you'll like https://github.com/danielnixon/eslint-plugin-total-functions/commit/12c7b78964ece4a6499c55282c74517426aad666

**Comment by danielnixon** [comment]
@tankers746 is it fair to say this change is less critical now?

**Comment by tankers746** [comment]
Yeah cheers, I have a few more ideas but I'll create another issue.
